# Generated by Django 2.0.3 on 2018-04-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku',)},
        ),
    ]
